apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag.fullname" . }}-secret
  labels:
    {{- include "rag.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "rag.databaseUrl" . | quote }}
  LLM_API_KEY: {{ .Values.secret.llmApiKey | quote }}
